version: 0.0
os: linux
files:
  - source: 'target'
    destination: '/home/ec2-user/server'
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: 'scripts/applicationStop.sh'
      timeout: 10
      runas: root
  ApplicationStart:
    - location: 'scripts/applicationStart.sh'
      timeout: 10
      runas: root
