version: 0.2
run-as: root
env:
  variables:
    env: 'build'
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - 'echo "Install phase executing..."'
      - 'yum install -y maven'
    finally:
      - 'echo "Taking exit from install phase"'
      - 'mvn -version'
  pre_build:
    commands:
      - 'echo "Pre_build phase executing..."'
    finally:
      - 'echo "Taking exit from pre_build phase"'
  build:
    commands:
      - 'echo "build phase executing..."'
      - 'mvn clean package'
    finally:
      - 'echo "Taking exit from build phase"'
  post_build:
    commands:
      - 'echo "post_build phase executing..."'
      - "echo 'mnv clean package' >> target/deploymentScript.sh"
      - 'chmod 777 target/deploymentScript.sh'
    finally:
      - 'echo "Taking exit from post_build phase"'

artifacts:
  files:
    - "target/webService.jar"
    - "scripts/*"
  s3-prefix: codeDeploy
